# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76621a01cc3c1f123efd4b91ed22eeb6d9dfe8275d6fc57ab128e83a8feaca44f54185a651136524075dfc8081f8b2033428d6fc4d8daa36803fd840bbf2aa99

test:
  secret_key_base: 2f597f6e441a39344b263c6ff8294fa545224ca4180dc6ed9a350dfd08d7fddff46f32615ed68be2aa0ab34e1ed55d036681a2a5b9b60cbb70fbf6f65605e198

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
